### ISSUE TITLE
Picture not found

### ISSUE THREAD

**Issue by zhaoxm469** [joeldenning/coexisting-vue-microfrontends#16]
I'm now under the navbar project, I'm going to put an image and I'm going to reference it on the page, and then I'm going to run project 5000, and it's going to show me the image's load path is 5000 and I can't find that image. How do you solve this?

**Comment by joeldenning** [comment]
Use webpack to give you the url to the image, and then use [dynamic webpack public path](https://webpack.js.org/guides/public-path/#on-the-fly) to ensure that webpack knows it's running on port 5000. Here are some more links that might help you:

- https://github.com/joeldenning/systemjs-webpack-interop
- https://github.com/joeldenning/coexisting-vue-microfrontends/blob/master/navbar/src/set-public-path.js
- https://single-spa.js.org/docs/faq.html#code-splits

Closing this because I think I've answered the question, but feel free to discuss this further here.
