### ISSUE TITLE
Standalone Mode

### ISSUE THREAD

**Issue by zero7u** [joeldenning/coexisting-vue-microfrontends#18]
Is there a way to run subapps independently, via some scripts in package.json?

**Comment by joeldenning** [comment]
No. Single-spa applications depend on each other by `import`'ing each other. Which means that they cannot operate as standalone apps.

Because of this, the recommended local development process is to have a deployed environment with all the microfrontends working. And then to use import-map-overrides to allow you to override one of the microfrontends at a time to load from your localhost. In this way, you avoid needing to boot up all the microfrontends locally just to develop one of them.

See https://github.com/joeldenning/coexisting-vue-microfrontends#local-development----one-app-at-a-time and https://github.com/joeldenning/import-map-overrides for more info.
