### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by linchanglin** [joeldenning/coexisting-vue-microfrontends#22]
I use single-spa, and single-spa-vue to integrate some vue(vue cli3) projects.  When I operate the integrated pages, the following error has occurred. Can you tell me the possible reasons? I look forward to your reply.

Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (<anonymous>)
    at _t (app.js:42)
    at s (app.js:42)
    at c (app.js:42)
    at u (app.js:42)
    at s (app.js:42)
    at c (app.js:42)
    at u (app.js:42)

**Comment by joeldenning** [comment]
It looks like you have an infinite loop. My guess is that this is not related to single-spa at all.

The `u` function is calling the `c` function which is calling the `s` function which then completes the infinite loop by calling the `u` function again.

To diagnose further, you'd need to share the contents of app.js line 42. Like I said previously, my guess is this is not related to single-spa (since it doesn't do regex stuff in it). But happy to be proven wrong if that's not the case 😄
