### ISSUE TITLE
how do you figure out the cross origin in microfrontends app1？

### ISSUE THREAD

**Issue by guguji5** [joeldenning/coexisting-vue-microfrontends#30]
where do you figure out the cross origin in microfrontends app1？

and where do you config the ’umd‘ type of build package in your demo project app1？

**Comment by joeldenning** [comment]
> where do you figure out the cross origin in microfrontends app1？

Could you help me understand this? What do you mean by "cross origin"?

> and where do you config the ’umd‘ type of build package in your demo project app1？

https://github.com/CanopyTax/vue-cli-plugin-single-spa/blob/1d4c9b530ba99cc03eea4725c8d205d6a5dab6ec/index.js#L14

**Comment by guguji5** [comment]
@joeldenning thanks for your replay. it answers my above two questions.

"cross origin" means that the browser has the "same origin policy" for security. Let take this git repo as an example, "localhost:5000" should not request the "localhost:8081/app" successfully, but it does. Because of the headers 'Access-Control-Allow-Origin': '*'.

I follow this document to run the microfrontends. When I try to add a my local demo as a sub project, the above two questions block me. It will be appreciated that the document cover these potential tips.

**Comment by joeldenning** [comment]
The following code shows how vue-cli-plugin-single-spa sets up CORS for webpack-dev-server, so that it can be downloaded from different requests.

https://github.com/CanopyTax/vue-cli-plugin-single-spa/blob/1d4c9b530ba99cc03eea4725c8d205d6a5dab6ec/index.js#L7-L10

I am closing this issue it doesn't seem like a bug with single-spa. Feel free to reopen or comment further.
