### ISSUE TITLE
Unexpected token '<'

### ISSUE THREAD

**Issue by 15982153332** [joeldenning/coexisting-vue-microfrontends#31]
npm run build
 production： use nginx
When the page is refreshed， Error occurred 
![image](https://user-images.githubusercontent.com/16485092/70431384-ed40b680-1ab7-11ea-9416-a15dd7a53094.png)

**Comment by joeldenning** [comment]
This error generally means that you are trying to download a JSON or javascript file but that the server is returning an HTML file. It can happen for your external import-map.json file, or it can be for one of your in-browser javascript modules.

The reason that this usually happens is that SPA servers are configured to return the index html file and an HTTP 200 instead of a 404 when they don't find a file.

Check your network tab and look at your import map's file, or your javascript files. One of them will be returning an html file instead of the correct file format.

**Comment by joeldenning** [comment]
Closing this since it's not an issue with single-spa or single-spa-vue, but just a common error with people's code. Feel free to comment further or reopen.
