### ISSUE TITLE
Issues with vue cli v4.x.x still happen

### ISSUE THREAD

**Issue by tvmota** [joeldenning/coexisting-vue-microfrontends#38]
### vue-cli version
![vue_version](https://user-images.githubusercontent.com/17927676/74897947-41e59500-5377-11ea-8686-8160d6975f2c.png)

### Project options
![vue_create_options](https://user-images.githubusercontent.com/17927676/74898085-9c7ef100-5377-11ea-8e9c-49bfb0106bce.png)

### Vue config
![vue_config_js](https://user-images.githubusercontent.com/17927676/74898107-ad2f6700-5377-11ea-83f1-0a635ec2dd26.png)

### Console log errors
![console_app3](https://user-images.githubusercontent.com/17927676/74898142-c9330880-5377-11ea-8bd9-cc45a9f5fa35.png)

I've cloned the [coexisting-vue-microfrontends](https://github.com/joeldenning/coexisting-vue-microfrontends) project, and created a new "module" (app3) with vue-cli v4.x.x, got the settings recommended in the issues here and the application does not render the new module. can you help me?
Follow the forked project:
[https://github.com/tvmota/coexisting-vue-microfrontends](https://github.com/tvmota/coexisting-vue-microfrontends)

Thank very much.

**Comment by joeldenning** [comment]
FYI, in the next week or so, I'm going to be archiving this repository in favor of the newer and better example at https://github.com/vue-microfrontends/. This will be part of the single-spa@5 release that is forthcoming.

Regarding the error you're experiencing, it is likely not related to vue cli 4. All of the applications in this repo also use vue cli 4.

I don't have the time right now to pull down your repo and debug it. The error indicates that the loading function for app3 is resolving with the webpackJsonp global variable array, instead of with the actual application. Webpack uses webpackJsonp as a way of doing code splits - it might have something to do with that.

**Comment by tvmota** [comment]
I've solved the problem by disabling code spliting, in vue.config.js:

`config.optimization.delete('splitChunks')`
![image](https://user-images.githubusercontent.com/17927676/75271997-e33b7380-57db-11ea-9af9-43a279e43e36.png)
Forked Repository [link](https://github.com/tvmota/coexisting-vue-microfrontends)
Thanks man.
