### ISSUE TITLE
one apps request

### ISSUE THREAD

**Issue by yangangzhang** [joeldenning/coexisting-vue-microfrontends#4]
hello,how to config  request in one  app?
![image](https://user-images.githubusercontent.com/20433039/63917680-bd702480-ca6d-11e9-897a-9c56fa40052e.png)

**Comment by joeldenning** [comment]
**For webpack assets, the answer is public path**

- https://single-spa.js.org/docs/faq.html#code-splits
- https://github.com/joeldenning/coexisting-vue-microfrontends/blob/master/app1/src/set-public-path.js
- https://webpack.js.org/guides/public-path/#on-the-fly

**For API requests, it's very unusual to change the location of your API requests depending on which app is making the request**. In a single page application architecture, your backend APIs should be decoupled from your frontend code. If you really want this functionality even though I find it unusual, you would use `__webpack_public_path__` as a prefix for your API requests.

Closing this since I think i've answered the question, but feel free to comment and discuss further if there is more to explore.

**Comment by yangangzhang** [comment]
Hello, maybe I didn't describe it clearly.Now, let me describe it again.
1. In app1, it has a request
```
created () {
    axios('/interface/user/getUserList').then((res) => {
      console.log(res)
    })
  }
```
2. In app1, vue.config.js
```
 devServer: {
        proxy: {
          "/interface": {
            target: "http://localhost:3000/",
            changeOrigin: true,
            pathRewrite: {
              "^/interface": "/interface"
            }
          }
        },
      }
```
3. I've started a 3000 port service locally.

**Now,checkout result in chrome**
![image](https://user-images.githubusercontent.com/20433039/64099096-0dffbe80-cd9b-11e9-931f-a72010924f1f.png)

The correct result should be shown in the following picture：
![image](https://user-images.githubusercontent.com/20433039/64099303-89617000-cd9b-11e9-8d81-56a6a0d9c5da.png)


I don't know if I have described it clearly.I'm confused by this problem. I've configured the proxy in devServer.

**Comment by joeldenning** [comment]
The reason that the request is failing is because it's going to the wrong domain. Your html file [is on port 5000](https://github.com/joeldenning/coexisting-vue-microfrontends/blob/master/root-html-file/package.json#L4), but your server is on port 3000.

In microfrontends, I would not recommend using webpack-dev-server proxying to make a request to your backend. The reason why is that you have multiple microfrontends, each running on their own port.

It is better to configure your code to call the backend directly, without going through a proxy. Two options for this:

1. Have your backend service serve your index.html file, so that requests to the backend are on the same host and port as the frontend code. For example, have your backend service on localhost:3000 *also serve the index.html file*, instead of using a static server for the index.html file.
2. Change your call to `/axios` have the fully qualified url. Example: `axios('http://localhost:3000/interface/user/getUserList')`. Dynamically change that domain for dev/prod environments by checking the browser's url to determine where the backend service is.

**Comment by yangangzhang** [comment]
**Thank you!** These two method can solve the problem.

I really want to use proxy in each one subApp,
Can you help me with a solution?

**Comment by joeldenning** [comment]
To use proxy, you have to change all of your axios calls to have `__webpack_public_path__` as part of the request url.

**Comment by yangangzhang** [comment]
> To use proxy, you have to change all of your axios calls to have `__webpack_public_path__` as part of the request url.

Thank you very much for your patience in answering my questions.

**Comment by joeldenning** [comment]
:thumbsup: I'm glad to hear you got it sorted out!
