### ISSUE TITLE
why do this in 'root-html-file/index.html'

### ISSUE THREAD

**Issue by mango-csl** [joeldenning/coexisting-vue-microfrontends#52]
> What error did you get?

i hava  a similar doubt

when i commented out this code in  ‘root-html-file/index.html’

```javascript
// 'root-html-file/index.html'

Promise.all([System.import('single-spa'), System.import('vue'), System.import('vue-router')]).then(function (modules) {   
    //var singleSpa = modules[0];
    //var Vue = modules[1];
    //var VueRouter = modules[2];
    //Vue.use(VueRouter)

```
it will be error to use router in  'navbar/src/App.vue'

```
this.$router.push('/navbar')
// this.$router   is  undefined
```
![image](https://user-images.githubusercontent.com/29364830/78220664-8591f980-74f4-11ea-8114-1a06b9e86515.png)

but it works  in vue-microfrontends[https://github.com/vue-microfrontends]

_Originally posted by @mango-csl in https://github.com/joeldenning/coexisting-vue-microfrontends/issues/37#issuecomment-607659665_

**Comment by joeldenning** [comment]
Hi @mango-csl - good question. You must call `Vue.use(VueRouter)` in order for `this.$router` to be defined. Commenting it out will cause errors. `vue` and `vue-router` are shared dependencies, which means that all microfrontends share the same instance and version of vue.

> but it works in [vue-microfrontends](https://github.com/vue-microfrontends)

That is because vue-microfrontends calls Vue.useRouter here:

- [navbar](https://github.com/vue-microfrontends/navbar/blob/686852a7bcfb6d01b6e3d688912c5f5a42b03862/src/router/index.js#L4)
- [rate-dogs](https://github.com/vue-microfrontends/rate-dogs/blob/master/src/router/index.js#L5)
- [dogs-dashboard](https://github.com/vue-microfrontends/dogs-dashboard/blob/master/src/router/index.js#L5)


Note how coexisting-vue-microfrontends does not call `Vue.use(VueRouter)` anywhere else besides the root config:

https://github.com/joeldenning/coexisting-vue-microfrontends/blob/master/app1/src/router.js#L4

I am closing this issue because I think I have explained what is happening. Feel free to reopen or comment further.

**Comment by mango-csl** [comment]
> Hi @mango-csl - good question. You must call `Vue.use(VueRouter)` in order for `this.$router` to be defined. Commenting it out will cause errors. `vue` and `vue-router` are shared dependencies, which means that all microfrontends share the same instance and version of vue.
> 
> > but it works in [vue-microfrontends](https://github.com/vue-microfrontends)
> 
> That is because vue-microfrontends calls Vue.useRouter here:
> 
> * [navbar](https://github.com/vue-microfrontends/navbar/blob/686852a7bcfb6d01b6e3d688912c5f5a42b03862/src/router/index.js#L4)
> * [rate-dogs](https://github.com/vue-microfrontends/rate-dogs/blob/master/src/router/index.js#L5)
> * [dogs-dashboard](https://github.com/vue-microfrontends/dogs-dashboard/blob/master/src/router/index.js#L5)
> 
> Note how coexisting-vue-microfrontends does not call `Vue.use(VueRouter)` anywhere else besides the root config:
> 
> https://github.com/joeldenning/coexisting-vue-microfrontends/blob/master/app1/src/router.js#L4
> 
> I am closing this issue because I think I have explained what is happening. Feel free to reopen or comment further.

thanks  , very interesting
