### ISSUE TITLE
Question: New Example Repo

### ISSUE THREAD

**Issue by tdowdle** [joeldenning/coexisting-vue-microfrontends#63]
You mention that the newer example repo better reflects the micro frontend architecture and is encouraged to use.

Can you explain the primary architectural differences between this example and the newer example?  What are some of the biggest or most significant changes?

Thank you

**Comment by joeldenning** [comment]
Hi @tdowdle, good question. The main thing with the new examples is that each microfrontend is in its own repo, has its own CI, and is independently deployable. Since independent deployments are one of the primary compelling reasons to do microfrontends for a lot of organizations, the new examples are nice for that. An additional feature of the new example is that it uses [utility microfrontends](https://single-spa.js.org/docs/recommended-setup#utility-modules-styleguide-api-etc), whereas this one does not. Last thing is that the microfrontends in the new example were created with create-single-spa, which is emerging as the recommended best practice for single-spa MFs.

**Comment by tdowdle** [comment]
Great, thank for you the insight @joeldenning 

Much appreciated.
